"""empty message

Revision ID: 258c9f2c684c
Revises: af51b66aceb1
Create Date: 2021-07-06 16:09:38.276481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258c9f2c684c'
down_revision = 'af51b66aceb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('hidden', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'hidden')
    # ### end Alembic commands ###
