"""empty message

Revision ID: af51b66aceb1
Revises: 3a3239533401
Create Date: 2021-07-04 21:08:58.840792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af51b66aceb1'
down_revision = '3a3239533401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'link_photo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'link_photo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
